<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $fillable = ['title','slug','thumbnail','description','content','view','is_published','especially'];

    public function categories(){
        return $this->belongsToMany(Category::class,'post_categories');
    }
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
    public function tags(){
        return $this->hasMany(Tag::class);
    }
}
